# live_monitor/signals/models/constants.py
"""
Constants used across signal processing
"""

# Signal value thresholds
STRONG_SIGNAL_THRESHOLD = 25
MEDIUM_SIGNAL_THRESHOLD = 10
WEAK_SIGNAL_THRESHOLD = 5

# Signal value ranges
MIN_SIGNAL_VALUE = -50
MAX_SIGNAL_VALUE = 50

# Confidence adjustments
BASE_CONFIDENCE = 0.5
CROSSOVER_CONFIDENCE_BOOST = 0.2
STRONG_TREND_CONFIDENCE_BOOST = 0.2
WEAK_TREND_CONFIDENCE_PENALTY = -0.1
GOOD_SPREAD_CONFIDENCE_BOOST = 0.1
EXTENDED_SPREAD_CONFIDENCE_PENALTY = -0.1
POSITION_ALIGNMENT_CONFIDENCE_BOOST = 0.1
MINIMUM_STRONG_SIGNAL_CONFIDENCE = 0.6

# Spread thresholds
TIGHT_SPREAD_THRESHOLD = 0.1
NORMAL_SPREAD_MIN = 0.3
NORMAL_SPREAD_MAX = 1.5
EXTENDED_SPREAD_THRESHOLD = 2.0

# Trend strength thresholds
STRONG_TREND_THRESHOLD = 70
WEAK_TREND_THRESHOLD = 30

# Magnitude adjustments
CROSSOVER_MAGNITUDE_BOOST = 1.2
CROSSOVER_AGAINST_TREND_PENALTY = 0.8
TIGHT_SPREAD_MAGNITUDE_PENALTY = 0.5
PRICE_POSITION_MISALIGNMENT_PENALTY = 0.7
VOLUME_CONFIRMATION_BOOST = 1.1

# Volatility adjusted strength thresholds
VERY_STRONG_VOL_ADJ_THRESHOLD = 2.0
NORMAL_VOL_ADJ_THRESHOLD = 1.0
DECENT_VOL_ADJ_THRESHOLD = 0.5